apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tetris-argo-app-3
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/timothepoznanski/testargocd.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: tetris-argo-3

  syncPolicy:
    syncOptions:
    - CreateNamespace=true  # If namespace doesn't exist, create it

    automated:  # Argocd will pull and apply changes from Git repo every 3 minutes (webhook can be configured to remove this delay)
      selfHeal: true  # Undo or overide (sync with git repo) any manual changes done on the cluster
      prune: true  # If component is renamed or deleted in files, Argo should do it on the cluster
