apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetris-argo-deployment-3
spec:
  selector:
    matchLabels:
      app: tetris-argo-3
  replicas: 4
  template:
    metadata:
      labels:
        app: tetris-argo-3
    spec:
      containers:
      - name: tetris-argo-3
        image: pozinux/tetris:1.0.0
        ports:
        - containerPort: 80
