apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetris-argo-deployment-2
spec:
  selector:
    matchLabels:
      app: tetris-argo-2
  replicas: 2
  template:
    metadata:
      labels:
        app: tetris-argo-2
    spec:
      containers:
      - name: tetris-argo-2
        image: pozinux/tetris:1.0.0
        ports:
        - containerPort: 80
