apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetris1argoapp
spec:
  selector:
    matchLabels:
      app: tetris1argoapp
  replicas: 2
  template:
    metadata:
      labels:
        app: tetrise1argoapp
    spec:
      containers:
      - name: tetris1argoapp
        image: pozinux/tetris:1.0.0
        ports:
        - containerPort: 80
