apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp3
spec:
  selector:
    matchLabels:
      app: myapp3
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp3
    spec:
      containers:
      - name: myapp3
        image: pozinux/tetris:1.0.0
        ports:
        - containerPort: 80
